/*document.write(Math.sqrt(9))
document.write("<br>")
document.write(Math.floor(5.66))
document.write("<br>")
document.write(Math.ceil(5.66))
document.write("<br>")
document.write(Math.abs(-25.25))
document.write("<br>")
document.write(Math.pow(2,5))
document.write("<br>")
document.write(Math.pow(2,5))
document.write("<br>")
document.write(Math.trunc(-5.66))
document.write("<br>")
document.write(Math.sign(-25.25))
document.write("<br>")*/
let a="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
document.write("length")
document.write("<br>")
document.write(a.slice(7,13))
document.write("<br>")
document.write('my name is "\\\kartik"')